[package]
name = "BRS"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.20.2"
regex = { version = "1.11.1", features = [] }

[[test]]
name = "tokenizer_tests"
path = "tests/tokenizer_test.rs"
