[package]
name = "BRS"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.20.2"
either = "1.13.0"

[[test]]
name = "tokenizer_tests"
path = "tests/tokenizer_test.rs"

[[test]]
name = "parser_tests"
path = "tests/parser_test.rs"
