name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64, aarch64]
        include:
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            rust_target: aarch64-unknown-linux-gnu
          - os: macos-latest
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            rust_target: aarch64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.rust_target }}

      - name: Install dependencies (Linux aarch64)
        if: matrix.arch == 'aarch64' && matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu
          
      - name: Build executable
        run: cargo build --target ${{ matrix.rust_target }} --verbose
      - name: Run
        run: run test.brs --target ${{ matrix.rust_target }} --verbose -- --outdir ../../target/debug/
      - name: Test executable
        run: ./../../target/debug/out
      - name: Run tests
        run: cargo test --target ${{ matrix.rust_target }} --verbose --tests
