name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [x86_64, aarch64]
        include:
          - os: ubuntu-latest
            arch: x86_64
            rust_target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            arch: aarch64
            rust_target: aarch64-unknown-linux-gnu
          - os: macos-latest
            arch: x86_64
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            arch: aarch64
            rust_target: aarch64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.rust_target }}

      - name: Install build dependencies
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y build-essential gcc

      - name: Install dependencies (Linux aarch64)
        if: matrix.arch == 'aarch64' && matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu

      - name: Install Xcode Command Line Tools (macOS)
        if: runner.os == 'macOS'
        run: xcode-select --install || true

      - name: Install Rust target
        run: rustup target add ${{ matrix.rust_target }}

      - name: Run
        run: | 
          cargo build --target ${{ matrix.rust_target }} --color=always --verbose --profile dev
          ls target
          ls target/${{ matrix.rust_target }}
          ls target/${{ matrix.rust_target }}/debug
          cargo run .github/workflows/run.brs --target ${{ matrix.rust_target }} --verbose -- --outdir target/debug/
      - name: Test
        run: |
          cargo build --color=always --verbose --tests --profile test
          cargo test --target ${{ matrix.rust_target }} --verbose --tests
